name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: JUnit Test Suite
      id: junit-test-suite
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: JUnit Test Suite
        setup-command: ''
        command: gradle test
        timeout: 5
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JUNIT-TEST-SUITE_RESULTS: "${{steps.junit-test-suite.outputs.result}}"
      with:
        runners: junit-test-suite
